name: CD

on:
  push:
    # TODO: testing
    # tags:
    #   - 'v*.*.*'
      

jobs:
  test:
    uses: ./.github/workflows/deploy.yml
    secrets:
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
